version: '3'

services:
  gateway_db:
    container_name: gateway_db
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${GATEWAY_DB_USER}
      PGUSER: ${GATEWAY_DB_USER}
      POSTGRES_PASSWORD: ${GATEWAY_DB_PASSWORD}
      POSTGRES_DB: ${GATEWAY_DB_NAME}
      PGDATABASE: ${GATEWAY_DB_NAME}
      PGPORT: ${GATEWAY_DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${GATEWAY_DB_PORT}:${GATEWAY_DB_PORT}"
    command: -p ${GATEWAY_DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - pinting_net

  gateway:
    container_name: gateway
    image: pinting/gateway:1.0.0
    restart: always
    build: .
    env_file:
      - ./env/.env
    ports:
      - '8080:8080'
    depends_on:
      gateway_db:
        condition: service_healthy
    networks:
      - pinting_net

networks:
  pinting_net:
    driver: bridge

# volumes:
  # gateway_db_vol:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ${GATEWAY_DB_VOL_PATH}