# syntax=docker/dockerfile:1

FROM alpine:3.19

ARG SSL_PATH=/etc/ssl/private

RUN apk update && \
    apk --no-cache add \
    nginx \
    openssl
    # dumb-init

RUN adduser -D pinting

# TODO: 실제 인증키 발급 로직으로 변경해야 함.
# RUN openssl genrsa -out ${SSL_PATH}/fresh_pong.key 2048 && \
#     openssl req -new -key ${SSL_PATH}/fresh_pong.key -out ${SSL_PATH}/fresh_pong.crt \
#     -subj "/C=KR/ST=Seoul/L=Gaepodong/O=pinting/OU=member/CN=pinting.com" && \
#     openssl x509 -req -days 1000 -in ${SSL_PATH}/fresh_pong.crt -signkey ${SSL_PATH}/fresh_pong.key -out ${SSL_PATH}/fresh_pong.crt && \
#     chown -R nginx ${SSL_PATH}

WORKDIR /var/www/html

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/default.conf /etc/nginx/http.d/default.conf

EXPOSE 80 443

CMD ["nginx"]